# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-25 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('friend_app', '0002_auto_20170725_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='friend_id',
        ),
        migrations.AddField(
            model_name='friends',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='friends',
            name='user',
        ),
        migrations.AddField(
            model_name='friends',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login_app.Users'),
            preserve_default=False,
        ),
    ]
